name: lint-build-deploy

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pylint --rcfile=.pylintrc src tests
  test:
    runs-on: ubuntu-latest
    needs: lint
    environment: main
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    strategy:
      matrix:
        python-version: ["3.12.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest tests
  build:
  # GCLOUD_CREDENTIALS
    runs-on: ubuntu-latest
    environment: main
    # TODO: uncomment this once we have tests
    # needs: test
    env:
      GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_CREDENTIALS }}
          registry: europe-west2-docker.pkg.dev
          project_id: heron-data-441322
          image_name: join-the-siege
          image_tag: latest, ${GITHUB_SHA:0:7}
          dockerfile: ./Dockerfile