name: lint-build-deploy

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pylint --rcfile=.pylintrc src tests
  test:
    runs-on: ubuntu-latest
    needs: lint
    environment: main
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.x
      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest tests
  build-push:
    runs-on: ubuntu-latest
    environment: main
    needs: test
    env:
      GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v4
      - name: Get short commit SHA
        id: get_short_sha
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_CREDENTIALS }}
          registry: europe-west2-docker.pkg.dev
          project_id: heron-data-441322
          image_name: join-the-siege/base
          image_tag: latest, ${{ steps.get_short_sha.outputs.SHORT_SHA }}
          dockerfile: ./Dockerfile
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    environment: main
    needs: build-push
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}
      - name: Get short commit SHA
        id: get_short_sha
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: GoogleCloudPlatform/github-actions/deploy-cloud-run@v1
        with:
          service: base
          image: europe-west2-docker.pkg.dev/heron-data-441322/join-the-siege/base:${{ steps.get_short_sha.outputs.SHORT_SHA }}
          region: europe-west2
          project_id: heron-data-441322
          env_vars: |-
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

